version: '3'
services:
  nginx:
    build: ./nginx
    restart: always
    ports:
      - 24842:80
      
    links:
      - app

  app:
    build: ./app
    restart: always
    environment:
      SLACK_SIGNING_SECRET: ${SLACK_SIGNING_SECRET}
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

    links:
      - db

  db:
    build: ./mysql
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      TZ: Asia/Seoul

    command:
      - --explicit_defaults_for_timestamp=1

volumes:
  mysql-data:
