CREATE TABLE IF NOT EXISTS restaurants (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    url VARCHAR(255) NOT NULL,
    count INT UNSIGNED NOT NULL,
    score FLOAT NOT NULL,
    last_changed TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
);
